
simple:
  default: true
  pages:
    - { tz: US/Pacific  }

results:
  tournament: 2018-mens-world-cup
  file_suffix: results
  pages:
    - { tz: US/Pacific, results: true  }
    - { tz: US/Pacific, results: false  }

navid:
  file_suffix: navid
  pages:
    - { tz: Asia/Tehran,         loc: fa    }
    - { tz: Europe/Amsterdam,    loc: fa    }
    - { tz: Europe/Amsterdam,    loc: en_GB }
    - { tz: Europe/Amsterdam,    loc: nl    }

tests:
  file_suffix: tests
  pages:
    - page_kind: groups_test
    - page_kind: days_test

designs:
  file_suffix: designs
  pages:
    - page_kind: cal_only
      variant: alpha
      match_numbers: true
      elimination_hints: false
      group_dots: false
    
    - variant: beta
      elimination_borders: false
      match_numbers: true
      elimination_hints: false
      group_dots: false
    
    - variant: borderless
      main_borders: false
    
    - variant: gold master

tourneys:
  all_tournaments: true
  pages:
    - { tz: US/Pacific  }
    - { tz: US/Pacific, results: true  }

langs:
  file_suffix: langs
  pages:
    - { tz: US/Pacific  }
    
    # European languages
    - { tz: Europe/London,       loc: en_GB }
    - { tz: Europe/Paris,        loc: fr    }
    - { tz: Europe/Rome,         loc: it    }
    - { tz: Europe/Berlin,       loc: de    }
    - { tz: Europe/Madrid,       loc: es_ES }
    - { tz: Europe/Amsterdam,    loc: nl    }
    
    # Persian variants
    - { tz: Asia/Tehran,         loc: fa    }
    
    # Asian/Pacific
    - { tz: Asia/Tokyo,          loc: ja    }
    - { tz: Australia/Sydney,    loc: en_AU }
    - { tz: Pacific/Auckland,    loc: en_NZ }

published:
  output_dir: published
  file_suffix: all
  unwind_pages: true
  pages:
    # US Timezones
    - { tz: US/Pacific  }
    - { tz: US/Mountain }
    - { tz: US/Central  }
    - { tz: US/Eastern  }

    # US in other languages

    - { tz: US/Pacific,          loc: ja    }
    - { tz: US/Mountain,         loc: ja    }
    - { tz: US/Central,          loc: ja    }
    - { tz: US/Eastern,          loc: ja    }
    
    # European languages
    - { tz: Europe/London,       loc: en_GB }
    - { tz: Europe/Paris,        loc: fr    }
    - { tz: Europe/Rome,         loc: it    }
    - { tz: Europe/Berlin,       loc: de    }
    - { tz: Europe/Madrid,       loc: es_ES }
    - { tz: Europe/Amsterdam,    loc: nl    }
    
    # Persian variants
    - { tz: Europe/Amsterdam,    loc: fa    }
    - { tz: Asia/Tehran,         loc: fa    }
    
    # Asian/Pacific
    - { tz: Asia/Tokyo,          loc: ja    }
    - { tz: Australia/Sydney,    loc: en_AU }
    - { tz: Pacific/Auckland,    loc: en_NZ }